name: My First Action Workflow

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: 25f1000098@ds.study.iitm.ac.in
        run: echo "Hello, world!"
